/*
 * Config.java
 *
 * Created on 1 novembre 2004, 21:54
 */

package mrteGest;
import java.io.*;
import java.util.*;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

/**
 *
 * @author  BOD
 */
public class ConfigCategorie extends javax.swing.JFrame
{
    
    /** Creates new form Config */
    
    Gestion laGestion;
    private static ConfigCategorie _instance;
    
    public static synchronized ConfigCategorie getInstance(Gestion pGestion)
    {
        if (_instance==null)
            _instance = new ConfigCategorie(pGestion);
        return _instance;
    }
    
    
    private ConfigCategorie(Gestion pGestion)
    {
        laGestion = pGestion;
        initComponents();
        for(int i = 0; i < pGestion.listeCategorie.size();i++)
            jComboBox1.addItem(pGestion.listeCategorie.get(i));
        jOperation.addItem("Remplacer par:");
        jOperation.addItem("Supprimer:");
        jOperation.addItem("Ajouter:");
        setVisible(true);
        setSize(700,75);
        setIconImage(Toolkit.getDefaultToolkit().createImage(Gestion.class.getResource("/LOGO.GIF")));
        addWindowListener(new WindowAdapter()
        {
            public void windowClosing(WindowEvent e)
            {
                enregistrerFic(laGestion.config);
                dispose();
                removeAll();
                _instance = null;
            }
        });
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents()//GEN-BEGIN:initComponents
    {
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jOperation = new javax.swing.JComboBox();
        lCat = new javax.swing.JLabel();
        tCat = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modification des licences");
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setText("Cat\u00e9gorie");
        jPanel1.add(jLabel1);

        jComboBox1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jComboBox1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jComboBox1ActionPerformed(evt);
            }
        });

        jPanel1.add(jComboBox1);

        jLabel4.setText("Op\u00e9ration");
        jPanel1.add(jLabel4);

        jOperation.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jOperationActionPerformed(evt);
            }
        });

        jPanel1.add(jOperation);

        lCat.setText("Nom");
        jPanel1.add(lCat);

        tCat.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                tCatActionPerformed(evt);
            }
        });

        jPanel1.add(tCat);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jButton1.setMnemonic('m');
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        getContentPane().add(jButton1, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents
    
    private void jOperationActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jOperationActionPerformed
    {//GEN-HEADEREND:event_jOperationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jOperationActionPerformed
    
    private void tCatActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_tCatActionPerformed
    {//GEN-HEADEREND:event_tCatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tCatActionPerformed
    
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (jOperation.getSelectedItem().equals("Supprimer:"))
        {
            
            Object[] options =
            { "Oui", "Non" };
            int reponse = JOptionPane.showOptionDialog(null, "Tous les adhérents ayant cette catégorie verront leur catégorie non renseignée.", "Attention", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE,null, options, options[0]);
            if(reponse == 0)
            {
                laGestion.jCategorie.removeItem(jComboBox1.getSelectedItem());
                laGestion.listeCategorie.remove(jComboBox1.getSelectedItem());
                
                //Suppression de la licence chez les adhérents
                ArrayList listeAttributs;
                for(int i = 0;i < laGestion.listeLigne.size();i++)
                {
                    listeAttributs = (ArrayList) laGestion.listeLigne.get(i);
                    if( (((String) listeAttributs.get(11)).toUpperCase()).equals(jComboBox1.getSelectedItem()) )
                    {
                        listeAttributs.remove(11);
                        listeAttributs.add(11,"");
                    }
                }
                jComboBox1.removeItem(jComboBox1.getSelectedItem());
                laGestion.bRecherche.doClick();
            }
        }
        //Cas du remplacement
        else if (jOperation.getSelectedItem().equals("Remplacer par:"))
        {
            if (!laGestion.listeCategorie.contains(tCat.getText()))
            {
                Object[] options =
                { "Oui", "Non" };
                int reponse = JOptionPane.showOptionDialog(null, "Tous les adhérents de cette catégorie la verront remplacée par '"+tCat.getText()+"'.", "Attention", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE,null, options, options[0]);
                if(reponse == 0)
                {
                    laGestion.jCategorie.removeItem(jComboBox1.getSelectedItem());
                    laGestion.listeCategorie.remove(jComboBox1.getSelectedItem());
                    
                    laGestion.jCategorie.addItem(tCat.getText());
                    laGestion.listeCategorie.add(tCat.getText());
                    
                    //Suppression de la catégorie chez les adhérents
                    ArrayList listeAttributs;
                    for(int i = 0;i < laGestion.listeLigne.size();i++)
                    {
                        listeAttributs = (ArrayList) laGestion.listeLigne.get(i);
                        if( (((String) listeAttributs.get(11)).toUpperCase()).equals(jComboBox1.getSelectedItem()) )
                        {
                            listeAttributs.remove(11);
                            listeAttributs.add(11,tCat.getText());
                        }
                    }
                    jComboBox1.removeItem(jComboBox1.getSelectedItem());
                    jComboBox1.addItem(tCat.getText());
                    laGestion.bRecherche.doClick();
                }
            }
            else
                JOptionPane.showMessageDialog(null, "Cette catégorie existe déjà.", "Attention", JOptionPane.ERROR_MESSAGE);
            
        }
        else
        {
            if (!laGestion.listeCategorie.contains(tCat.getText()))
            {
                laGestion.jCategorie.addItem(tCat.getText());
                laGestion.listeCategorie.add(tCat.getText());
                jComboBox1.addItem(tCat.getText());
            }
            else
                JOptionPane.showMessageDialog(null, "Cette catégorie existe déjà.", "Attention", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    public void enregistrerFic(File fichier)
    {
        try
        {
            fichier.createNewFile();
            
            FileWriter ecrivain = new FileWriter(fichier);
            String attribut = null;
            
            for(int i = 0;i < laGestion.listeCategorie.size();i++)
            {
                attribut = (String) laGestion.listeCategorie.get(i);
                ecrivain.write(attribut+"$",0,attribut.length()+1);
            }
            ecrivain.write(13);
            ecrivain.write(10);
            
            for(int i = 0;i < laGestion.listeLic.size();i++)
            {
                attribut = (String) laGestion.listeLic.get(i);
                ecrivain.write(attribut+"$",0,attribut.length()+1);
                attribut = (String) laGestion.listePrixLic.get(i);
                ecrivain.write(attribut+"$",0,attribut.length()+1);
            }
            ecrivain.write(13);
            ecrivain.write(10);
            
            ecrivain.flush();
            ecrivain.close();
            //JOptionPane.showMessageDialog(null, "Sauvegarde effectuée.", "Info", JOptionPane.INFORMATION_MESSAGE);
        }//try
        
        catch(IOException eIo)
        {
            JOptionPane.showMessageDialog(null, "Impossible d'écrire sur le fichier de sauvegarde.", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
        
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox jOperation;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lCat;
    private javax.swing.JTextField tCat;
    // End of variables declaration//GEN-END:variables
    
}
