/*
 * Config.java
 *
 * Created on 1 novembre 2004, 21:54
 */

package mrteGest;
import java.io.*;
import java.util.*;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

/**
 *
 * @author  BOD
 */
public class ConfigLicence extends javax.swing.JFrame
{
    
    /** Creates new form Config */
    
    Gestion laGestion;
    private static ConfigLicence _instance;
    
    public static synchronized ConfigLicence getInstance(Gestion pGestion)
    {
        if (_instance==null)
            _instance = new ConfigLicence(pGestion);
        return _instance;
    }
    
    
    private ConfigLicence(Gestion pGestion)
    {
        laGestion = pGestion;
        initComponents();
        for(int i = 0; i < pGestion.listeLic.size();i++)
            jComboBox1.addItem(pGestion.listeLic.get(i));
        jOperation.addItem("Remplacer par:");
        jOperation.addItem("Supprimer:");
        jOperation.addItem("Ajouter:");
        setIconImage(Toolkit.getDefaultToolkit().createImage(Gestion.class.getResource("LOGO.GIF")));
        setVisible(true);
        addWindowListener(new WindowAdapter()
        {
            public void windowClosing(WindowEvent e)
            {
                enregistrerFic(laGestion.config);
                dispose();
                removeAll();
                _instance = null;
            }
        });
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents()//GEN-BEGIN:initComponents
    {
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jOperation = new javax.swing.JComboBox();
        lLic = new javax.swing.JLabel();
        tLic = new javax.swing.JTextField();
        lLicPrix = new javax.swing.JLabel();
        tLicPrix = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modification des licences");
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new java.awt.GridLayout(2, 0));

        jLabel1.setText("Type de licence");
        jPanel1.add(jLabel1);

        jComboBox1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jComboBox1ActionPerformed(evt);
            }
        });

        jPanel1.add(jComboBox1);

        jLabel4.setText("Op\u00e9ration");
        jPanel1.add(jLabel4);

        jPanel1.add(jOperation);

        lLic.setText("Nom de la licence");
        jPanel1.add(lLic);

        tLic.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                tLicActionPerformed(evt);
            }
        });

        jPanel1.add(tLic);

        lLicPrix.setText("Prix de la licence");
        jPanel1.add(lLicPrix);

        tLicPrix.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                tLicPrixActionPerformed(evt);
            }
        });
        tLicPrix.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                tLicPrixFocusLost(evt);
            }
        });

        jPanel1.add(tLicPrix);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        getContentPane().add(jButton1, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents
    
    private void tLicPrixFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_tLicPrixFocusLost
    {//GEN-HEADEREND:event_tLicPrixFocusLost
        // TODO add your handling code here:
        try
        {
            Double.parseDouble(tLicPrix.getText());
        }
        catch(NumberFormatException nE)
        {
            
            tLicPrix.setForeground(Color.RED);
            tLicPrix.setText("Numérique!");
            tLicPrix.requestFocus();
            //JOptionPane.showMessageDialog(this,"Vous devez rentrer un format numérique avec ',' si besoin.","Attention",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_tLicPrixFocusLost
    
    private void tLicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tLicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tLicActionPerformed
    
    private void tLicPrixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tLicPrixActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tLicPrixActionPerformed
    
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (jOperation.getSelectedItem().equals("Supprimer:"))
        {
            
            Object[] options =
            { "Oui", "Non" };
            int reponse = JOptionPane.showOptionDialog(null, "Tous les adhérents ayant cette licence verront leur licence non renseignée.", "Attention", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE,null, options, options[0]);
            if(reponse == 0)
            {
                laGestion.jLic.removeItem(jComboBox1.getSelectedItem());
                laGestion.listeLic.remove(jComboBox1.getSelectedItem());
                laGestion.listePrixLic.remove(jComboBox1.getSelectedIndex());
                
                //Suppression de la licence chez les adhérents
                ArrayList listeAttributs;
                for(int i = 0;i < laGestion.listeLigne.size();i++)
                {
                    listeAttributs = (ArrayList) laGestion.listeLigne.get(i);
                    if( (((String) listeAttributs.get(8)).toUpperCase()).equals(jComboBox1.getSelectedItem()) )
                    {
                        listeAttributs.remove(8);
                        listeAttributs.add(8,"");
                        listeAttributs.remove(9);
                        listeAttributs.add(9,"");
                    }
                }
                jComboBox1.removeItem(jComboBox1.getSelectedItem());
                laGestion.bRecherche.doClick();
            }
        }
        //Cas du remplacement
        else if (jOperation.getSelectedItem().equals("Remplacer par:"))
        {
//            if (!laGestion.listeLic.contains(tLic.getText()))
//            {
                Object[] options =
                { "Oui", "Non" };
                int reponse = JOptionPane.showOptionDialog(null, "Tous les adhérents ayant cette licence verront leur licence remplacée par"+tLic.getText()+".", "Attention", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE,null, options, options[0]);
                if(reponse == 0)
                {
                    laGestion.jLic.removeItem(jComboBox1.getSelectedItem());
                    laGestion.listeLic.remove(jComboBox1.getSelectedItem());
                    laGestion.listePrixLic.remove(jComboBox1.getSelectedIndex());
                    
                    laGestion.jLic.addItem(tLic.getText());
                    laGestion.listeLic.add(tLic.getText());
                    laGestion.listePrixLic.add(tLicPrix.getText());
                    
                    //Suppression de la licence chez les adhérents
                    ArrayList listeAttributs;
                    for(int i = 0;i < laGestion.listeLigne.size();i++)
                    {
                        listeAttributs = (ArrayList) laGestion.listeLigne.get(i);
                        if( (((String) listeAttributs.get(8)).toUpperCase()).equals(jComboBox1.getSelectedItem()) )
                        {
                            listeAttributs.remove(8);
                            listeAttributs.add(8,tLic.getText());
                            listeAttributs.remove(9);
                            listeAttributs.add(9,tLicPrix.getText());
                        }
                    }
                    jComboBox1.removeItem(jComboBox1.getSelectedItem());
                    jComboBox1.addItem(tLic.getText());
                    laGestion.bRecherche.doClick();
                }
//            }
//            else
//                JOptionPane.showMessageDialog(null, "Cette licence existe déjà.", "Attention", JOptionPane.ERROR_MESSAGE);
            
        }
        else
        {
            if (!laGestion.listeLic.contains(tLic.getText()))
            {
                laGestion.jLic.addItem(tLic.getText());
                laGestion.listeLic.add(tLic.getText());
                laGestion.listePrixLic.add(tLicPrix.getText());
                jComboBox1.addItem(tLic.getText());
            }
            else
                JOptionPane.showMessageDialog(null, "Cette licence existe déjà.", "Attention", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Config().setVisible(true);
            }
        });
    }*/
    
    public void enregistrerFic(File fichier)
    {
        try
        {
            fichier.createNewFile();
            
            FileWriter ecrivain = new FileWriter(fichier);
            String attribut = null;
            
            for(int i = 0;i < laGestion.listeCategorie.size();i++)
            {
                attribut = (String) laGestion.listeCategorie.get(i);
                ecrivain.write(attribut+"$",0,attribut.length()+1);
            }
            ecrivain.write(13);
            ecrivain.write(10);
            
            for(int i = 0;i < laGestion.listeLic.size();i++)
            {
                attribut = (String) laGestion.listeLic.get(i);
                ecrivain.write(attribut+"$",0,attribut.length()+1);
                attribut = (String) laGestion.listePrixLic.get(i);
                ecrivain.write(attribut+"$",0,attribut.length()+1);
            }
            ecrivain.write(13);
            ecrivain.write(10);
            
            ecrivain.flush();
            ecrivain.close();
            //JOptionPane.showMessageDialog(null, "Sauvegarde effectuée.", "Info", JOptionPane.INFORMATION_MESSAGE);
        }//try
        
        catch(IOException eIo)
        {
            JOptionPane.showMessageDialog(null, "Impossible d'écrire sur le fichier de sauvegarde.", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
        
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox jOperation;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lLic;
    private javax.swing.JLabel lLicPrix;
    private javax.swing.JTextField tLic;
    private javax.swing.JTextField tLicPrix;
    // End of variables declaration//GEN-END:variables
    
}
